# Generated by Django 4.2.20 on 2025-03-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=6),
        ),
        migrations.AlterField(
            model_name='homework',
            name='hw_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ta',
            name='first',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ta',
            name='last',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ta',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tacourserel',
            name='classification',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('GR', 'Graduate')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('hw_name', 'course_offering')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('hw', 'question_name')},
        ),
    ]
