# Generated by Django 4.2.20 on 2025-03-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_courseoffering_semester_alter_homework_hw_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
